name: Lint CI

on:
  workflow_call:
    inputs:
      lint:
        description: 'Set to true to run linting scripts.'
        required: false
        default: false
        type: boolean

jobs:
  linter:
    name: Lint Code
    if: >
      !failure() &&
      !cancelled() &&
      inputs.lint == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm i --ignore-scripts

      - name: Lint code
        run: npm run lint
