name: Test with PostgreSQL

on:
  workflow_call:
    inputs:
      db-migrations:
        description: 'Run database migrations.'
        required: false
        default: true
        type: boolean
      db-seed:
        description: 'Run database seeding.'
        required: false
        default: true
        type: boolean

jobs:
  container-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run DB migrations
        if: >
          !failure() &&
          !cancelled() &&
          inputs.db-migrations == true
        run: npm run db:migrate 
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

      - name: Run DB seeds
        if: >
          !failure() &&
          !cancelled() &&
          inputs.db-seed == true
        run: npm run db:seed 
        env: 
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"

      - name: Run tests
        run: npm run test
        env: 
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
